package com.example.mddanish.myapplication;

import android.app.Activity;
import android.os.Bundle;
import android.text.Html;
import android.widget.TextView;

/**
 * Created by MD DANISH on 02-01-2017.
 */
public class Constructor extends Activity {
    TextView tv;

    public Constructor()
    {
    }

    protected void onCreate(Bundle bundle)
    {
        super.onCreate(bundle);
        setContentView(R.layout.constructor);
        tv = (TextView) findViewById(R.id.textView1);
        tv.setText(Html.fromHtml("<h1><font color=#ff0000>Constructors in Java </font></h1>Constructor is a block of code that allows you to create an object of class. This can also be called creating an instance. Constructor looks like a method but it\u2019s not, for example methods can have any return type or no return type (considered as void) but constructors don\u2019t have any return type not even void.<b><br></br><br></br><font color=#82E0AA ><big>Rules for creating java constructor</big></b></font></font><br></br><br></br>There are basically two rules defined for the constructor.<br></br><br></br><b><font color=#D2B4DE>1.</font></b>Constructor name must be same as its class name<br></br><br></br><b><font color=#D2B4DE>2.</font></b>Constructor must have no explicit return type<br></br><b><br></br><font color=#82E0AA ><big>Types of Constructors</big></b></font></font><br></br><br></br><b><font color=#D2B4DE>1.</font></b>Default constructor (no-arg constructor)<br></br><br></br><b><font color=#D2B4DE>2.</font></b>Parameterized constructor<br></br><b><br></br><font color=#82E0AA ><big>Default constructor</big></b></font></font><br></br><br></br>In Java default constructor refers to a nullary constructor that is automatically generated by the compiler if no constructors have been defined for the class. The default constructor implicitly calls the superclass's nullary constructor, then executes an empty body.<br></br><b><br></br><font color=#82E0AA ><big>Parameterized constructor</big></b></font></font><br></br><br></br>Parameterized constructors are required to pass parameters on creation of objects.If we define only parameterized constructors, then we cannot create an object with default constructor. This is because compiler will not create default constructor. You need to create default constructor explicitly."));
    }
}
